import numpy as np
x = np.array([1, 2, 3, 4, 5])
print("x:", x)
print("x + 5:", x + 5)
print("x * 2:", x * 2)
print("x ** 2:", x ** 2)
print("x > 2:", x > 2)
print("x[x > 2]:", x[x > 2])
print("x.sum():", x.sum())
print("x.mean():", x.mean())
print("x.std():", x.std())
print("x.max():", x.max())
print("x.min():", x.min())
print("x[2:4]:", x[2:4])
print("x[1:4:2]:", x[1:4:2])
print("x[::-1]:", x[::-1])
print("x.reshape(5, 1):", x.reshape(5, 1))
print("x.reshape(1, 5):", x.reshape(1, 5))
print("x.T:", x.T)
print("np.dot(x, x):", np.dot(x, x))
print("np.sum(x):", np.sum(x))
print("np.sin(x):", np.sin(x))
print("np.cos(x):", np.cos(x))
print("np.exp(x):", np.exp(x))

np.random.randint